src/ITCE.SNOW.FoundationData/Controllers/ExportController.cs
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CsvHelper;
using ITCE.SNOW.Data.AzureDataTable;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace ITCE.SNOW.FoundationData.Controllers
{
    public class ExportController : Controller
    {
        private readonly DataTableStorageRepository _dataRepository;

        public ExportController(IOptions<DataTableSettings> dataTableSettings)
        {
            //This is dirty, but DI will come later
            _dataRepository = new DataTableStorageRepository(dataTableSettings.Value);
        }

        public async Task<FileResult> SupportGroups()
        {
            using (var stream = new MemoryStream())
            {
                using (var writer = new StreamWriter(stream))
                {
                    var csvWriter = new CsvWriter(writer)
                    {
                        Configuration =
                        {
                            HasHeaderRecord = true,
                            Encoding = Encoding.UTF8
                        }
                    };
                    var supportGroups = _dataRepository.GetSupportGroups().ToList();
                    csvWriter.WriteRecords(supportGroups);
                    writer.Flush();

                    var fileBytes = stream.ToArray();
                    const string fileName = "supportGroups.csv";
                    writer.Close();
                    stream.Close();
                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
                }
            }
        }
        public async Task<FileResult> SupportGroupMembers()
        {
            using (var stream = new MemoryStream())
            {
                using (var writer = new StreamWriter(stream))
                {
                    var csvWriter = new CsvWriter(writer)
                    {
                        Configuration =
                        {
                            HasHeaderRecord = true,
                            Encoding = Encoding.UTF8
                        }
                    };
                    var members = _dataRepository.GetSupportGroupMembers().ToList();
                    csvWriter.WriteRecords(members);
                    writer.Flush();

                    var fileBytes = stream.ToArray();
                    const string fileName = "supportGroupMembers.csv";
                    writer.Close();
                    stream.Close();
                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
                }
            }
        }
        public async Task<FileResult> BusinessServices()
        {
            using (var stream = new MemoryStream())
            {
                using (var writer = new StreamWriter(stream))
                {
                    var csvWriter = new CsvWriter(writer)
                    {
                        Configuration =
                        {
                            HasHeaderRecord = true,
                            Encoding = Encoding.UTF8
                        }
                    };
                    var services = _dataRepository.GetBusinessServices().ToList();
                    csvWriter.WriteRecords(services);
                    writer.Flush();

                    var fileBytes = stream.ToArray();
                    const string fileName = "businessServices.csv";
                    writer.Close();
                    stream.Close();
                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
                }
            }
        }
        public async Task<FileResult> ServiceCatalogRequests()
        {
            using (var stream = new MemoryStream())
            {
                using (var writer = new StreamWriter(stream))
                {
                    var csvWriter = new CsvWriter(writer)
                    {
                        Configuration =
                        {
                            HasHeaderRecord = true,
                            Encoding = Encoding.UTF8
                        }
                    };
                    var requests = _dataRepository.GetServiceCatalogRequests().ToList();
                    csvWriter.WriteRecords(requests);
                    writer.Flush();

                    var fileBytes = stream.ToArray();
                    const string fileName = "serviceCatalogRequests.csv";
                    writer.Close();
                    stream.Close();
                    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
                }
            }
        }
    }
}

src/ITCE.SNOW.FoundationData/Controllers/ValidationController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ITCE.SNOW.Data.AzureDataTable;
using ITCE.SNOW.Data.Excel;
using ITCE.SNOW.Data.ServiceNow.ServiceNow.Configuration;
using ITCE.SNOW.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace ITCE.SNOW.FoundationData.Controllers
{
    public class ValidationController : Controller
    {
        private readonly ValidationService _validationService;
        private readonly DataTableStorageRepository _dataRepository;

        public ValidationController(IOptions<ServiceNowConfiguration> serviceNowConfigurationOptions, IOptions<DataTableSettings> dataTableSettings)
        {
            //This is dirty, but DI will come later
            _validationService = new ValidationService(serviceNowConfigurationOptions.Value);
            _dataRepository = new DataTableStorageRepository(dataTableSettings.Value);
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(ICollection<IFormFile> files)
        {
            var validationSummaries = new List<object>();
            var repository = new FoundationDataRepository();
            
            foreach (var file in files.Where(file => file.Length > 0))
            {
                using (var stream = file.OpenReadStream())
                {
                        
                    var groupsStream = new MemoryStream();
                    var businessServicesStream = new MemoryStream();
                    var requestsStream = new MemoryStream();

                    await CopyToAsync(stream, groupsStream).ConfigureAwait(true);
                    var groups = repository.GetSupportGroups(groupsStream);
                    await CopyToAsync(stream, businessServicesStream).ConfigureAwait(true);
                    var services = repository.GetBusinessServices(businessServicesStream);
                    await CopyToAsync(stream, requestsStream).ConfigureAwait(true);
                    var requests = repository.GetServicePortalRequests(requestsStream);
                    validationSummaries.Add(_validationService.ValidateSupportGroups(groups));
                    validationSummaries.Add(_validationService.ValidateBusinessServices(services,groups));
                    validationSummaries.Add(_validationService.ValidateServiceCatalogRequests(requests,groups,services));
                    ViewBag.ValidationSummaries = validationSummaries;
                    stream.Close();
                    await _dataRepository.StoreSupportGroups(groups).ConfigureAwait(true);
                    await _dataRepository.StoreSupportGroupsMmembers(groups).ConfigureAwait(true);
                    await _dataRepository.StoreBusinessServices(services).ConfigureAwait(true);
                    await _dataRepository.StoreServicePortalRequests(requests).ConfigureAwait(true);
                }
            }
            return View();
        }

        private async Task CopyToAsync(Stream stream, MemoryStream targetStream)
        {
            stream.Seek(0, SeekOrigin.Begin);
            await stream.CopyToAsync(targetStream).ConfigureAwait(true);
            targetStream.Seek(0, SeekOrigin.Begin);
        }
    }
}

src/ITCE.SNOW.FoundationData/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.Extensibility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITCE.SNOW.FoundationData</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - ITCE.SNOW.FoundationData</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/ITCE.SNOW.FoundationData/Views/Validation/Index.cshtml
@using System.Collections.Generic
@using ITCE.SNOW.Domain
@using ITCE.SNOW.Domain.Validation
@if (ViewBag.validationSummaries == null)
{
    <div class="bg-info" style="padding: 10px;">
        <h4>Instructions</h4>
        Delete all rows before the black header row in the template. Make sure the black row is the starting row for all sheets.<br/>
        Make sure that the sheets and their columns are named as follows:
        <ul>
            <li>
                Support Groups
                <ul>
                    <li>Country</li>
                    <li>Group Name</li>
                    <li>Manager Name</li>
                    <li>Group Email</li>
                    <li>Group Members (one row for each member)</li>
                </ul>
            </li>
            <li>
                Business Services
                <ul>
                    <li>Country</li>
                    <li>Name</li>
                    <li>Assignment Group US</li>
                    <li>Assignment Group GR</li>
                    <li>Business Criticality US</li>
                    <li>Business Criticality GR</li>
                    <li>Comments</li>
                    <li>Managed By US</li>
                    <li>Managed By GR</li>
                </ul>
            </li>
            <li>
                ServicePortalRequests
                <ul>
                    <li>Country</li>
                    <li>Self-service portal category</li>
                    <li>Self-service portal sub category</li>
                    <li>Request  Name</li>
                    <li>Related Business Service</li>
                    <li>Description</li>
                    <li>Approver (Person, or role, e.g. Line Manager)</li>
                    <li>Implementer Group</li>
                    <li>Department name (if only specific department should see this entry)</li>
                </ul>
            </li>
        </ul>
    </div>
}
<form method="post" asp-action="Index" asp-controller="Validation" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Upload" />
</form>

@if (ViewBag.validationSummaries != null)
{
    var summaries = ViewBag.validationSummaries as List<object>;
    if (summaries != null)
    {
        foreach (var summary in summaries)
        {
            if (summary is IValidationSummary<SupportGroup>)
            {
                var supportGroupSummary = summary as IValidationSummary<SupportGroup>;
                <p>Validation for: @supportGroupSummary.Name</p>
                <hr />
                foreach (var validationMessage in supportGroupSummary.Messages)
                {
                    <p><strong>@Html.Raw(validationMessage.Message)</strong>
                        <br/>reference: @validationMessage.Reference.Reference</p>
                }
            }
            if (summary is IValidationSummary<BusinessService>)
            {
                var businessServiceSummary = summary as IValidationSummary<BusinessService>;
                <p>Validation for: @businessServiceSummary.Name</p>
                <hr />
                foreach (var validationMessage in businessServiceSummary.Messages)
                {
                    <p>
                        <strong>@Html.Raw(validationMessage.Message)</strong>
                        <br />reference: @validationMessage.Reference.Reference
                    </p>
                }
            }
            if (summary is IValidationSummary<ServicePortalRequest>)
            {
                var serviceRequestSummary = summary as IValidationSummary<ServicePortalRequest>;
                <p>Validation for: @serviceRequestSummary.Name</p>
                <hr />
                foreach (var validationMessage in serviceRequestSummary.Messages)
                {
                    <p>
                        <strong>@Html.Raw(validationMessage.Message)</strong>
                        <br />reference: @validationMessage.Reference.Reference
                    </p>
                }
            }
        }
    }
}
@if (ViewBag.validationSummaries != null)
{
    <p  class="bg-warning" style="padding: 10px;">Once you are sure everything is valid you can export the following CSV files for ServiceNow:
    </p>
    <ul>
        <li><a href="/export/supportgroups">Support Groups</a></li>
        <li><a href="/export/supportgroupmembers">Support Group Members</a></li>
        <li><a href="/export/businessservices">Business Services</a></li>
        <li><a href="/export/ServiceCatalogRequests">Service Catalog Requests</a></li>
    </ul>
}